// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: app/src/main/java/com/example/gitsample/system/proto/core/InfoValue.proto
// Protobuf Java Version: 4.29.3

package com.example.gitsample.system.proto.data;

public final class InfoValueOuterClass {
  private InfoValueOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface InfoValueOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.InfoValue)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int32 index = 1;</code>
     * @return The index.
     */
    int getIndex();

    /**
     * <code>string infoValue = 2;</code>
     * @return The infoValue.
     */
    java.lang.String getInfoValue();
    /**
     * <code>string infoValue = 2;</code>
     * @return The bytes for infoValue.
     */
    com.google.protobuf.ByteString
        getInfoValueBytes();
  }
  /**
   * Protobuf type {@code proto.InfoValue}
   */
  public  static final class InfoValue extends
      com.google.protobuf.GeneratedMessageLite<
          InfoValue, InfoValue.Builder> implements
      // @@protoc_insertion_point(message_implements:proto.InfoValue)
      InfoValueOrBuilder {
    private InfoValue() {
      infoValue_ = "";
    }
    public static final int INDEX_FIELD_NUMBER = 1;
    private int index_;
    /**
     * <code>int32 index = 1;</code>
     * @return The index.
     */
    @java.lang.Override
    public int getIndex() {
      return index_;
    }
    /**
     * <code>int32 index = 1;</code>
     * @param value The index to set.
     */
    private void setIndex(int value) {
      
      index_ = value;
    }
    /**
     * <code>int32 index = 1;</code>
     */
    private void clearIndex() {

      index_ = 0;
    }

    public static final int INFOVALUE_FIELD_NUMBER = 2;
    private java.lang.String infoValue_;
    /**
     * <code>string infoValue = 2;</code>
     * @return The infoValue.
     */
    @java.lang.Override
    public java.lang.String getInfoValue() {
      return infoValue_;
    }
    /**
     * <code>string infoValue = 2;</code>
     * @return The bytes for infoValue.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getInfoValueBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(infoValue_);
    }
    /**
     * <code>string infoValue = 2;</code>
     * @param value The infoValue to set.
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setInfoValue(
        java.lang.String value) {
      value.getClass();  // minimal bytecode null check

      infoValue_ = value;
    }
    /**
     * <code>string infoValue = 2;</code>
     */
    private void clearInfoValue() {

      infoValue_ = getDefaultInstance().getInfoValue();
    }
    /**
     * <code>string infoValue = 2;</code>
     * @param value The bytes for infoValue to set.
     */
    private void setInfoValueBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      infoValue_ = value.toStringUtf8();

    }

    public static com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code proto.InfoValue}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue, Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.InfoValue)
        com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValueOrBuilder {
      // Construct using com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int32 index = 1;</code>
       * @return The index.
       */
      @java.lang.Override
      public int getIndex() {
        return instance.getIndex();
      }
      /**
       * <code>int32 index = 1;</code>
       * @param value The index to set.
       * @return This builder for chaining.
       */
      public Builder setIndex(int value) {
        copyOnWrite();
        instance.setIndex(value);
        return this;
      }
      /**
       * <code>int32 index = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIndex() {
        copyOnWrite();
        instance.clearIndex();
        return this;
      }

      /**
       * <code>string infoValue = 2;</code>
       * @return The infoValue.
       */
      @java.lang.Override
      public java.lang.String getInfoValue() {
        return instance.getInfoValue();
      }
      /**
       * <code>string infoValue = 2;</code>
       * @return The bytes for infoValue.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getInfoValueBytes() {
        return instance.getInfoValueBytes();
      }
      /**
       * <code>string infoValue = 2;</code>
       * @param value The infoValue to set.
       * @return This builder for chaining.
       */
      public Builder setInfoValue(
          java.lang.String value) {
        copyOnWrite();
        instance.setInfoValue(value);
        return this;
      }
      /**
       * <code>string infoValue = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearInfoValue() {
        copyOnWrite();
        instance.clearInfoValue();
        return this;
      }
      /**
       * <code>string infoValue = 2;</code>
       * @param value The bytes for infoValue to set.
       * @return This builder for chaining.
       */
      public Builder setInfoValueBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setInfoValueBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.InfoValue)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "index_",
              "infoValue_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0004\u0002\u0208" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue> parser = PARSER;
          if (parser == null) {
            synchronized (com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:proto.InfoValue)
    private static final com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue DEFAULT_INSTANCE;
    static {
      InfoValue defaultInstance = new InfoValue();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        InfoValue.class, defaultInstance);
    }

    public static com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<InfoValue> PARSER;

    public static com.google.protobuf.Parser<InfoValue> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface InfoValueListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.InfoValueList)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * 对象列表
     * </pre>
     *
     * <code>repeated .proto.InfoValue infoList = 1;</code>
     */
    java.util.List<com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue> 
        getInfoListList();
    /**
     * <pre>
     * 对象列表
     * </pre>
     *
     * <code>repeated .proto.InfoValue infoList = 1;</code>
     */
    com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue getInfoList(int index);
    /**
     * <pre>
     * 对象列表
     * </pre>
     *
     * <code>repeated .proto.InfoValue infoList = 1;</code>
     */
    int getInfoListCount();
  }
  /**
   * Protobuf type {@code proto.InfoValueList}
   */
  public  static final class InfoValueList extends
      com.google.protobuf.GeneratedMessageLite<
          InfoValueList, InfoValueList.Builder> implements
      // @@protoc_insertion_point(message_implements:proto.InfoValueList)
      InfoValueListOrBuilder {
    private InfoValueList() {
      infoList_ = emptyProtobufList();
    }
    public static final int INFOLIST_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue> infoList_;
    /**
     * <pre>
     * 对象列表
     * </pre>
     *
     * <code>repeated .proto.InfoValue infoList = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue> getInfoListList() {
      return infoList_;
    }
    /**
     * <pre>
     * 对象列表
     * </pre>
     *
     * <code>repeated .proto.InfoValue infoList = 1;</code>
     */
    public java.util.List<? extends com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValueOrBuilder> 
        getInfoListOrBuilderList() {
      return infoList_;
    }
    /**
     * <pre>
     * 对象列表
     * </pre>
     *
     * <code>repeated .proto.InfoValue infoList = 1;</code>
     */
    @java.lang.Override
    public int getInfoListCount() {
      return infoList_.size();
    }
    /**
     * <pre>
     * 对象列表
     * </pre>
     *
     * <code>repeated .proto.InfoValue infoList = 1;</code>
     */
    @java.lang.Override
    public com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue getInfoList(int index) {
      return infoList_.get(index);
    }
    /**
     * <pre>
     * 对象列表
     * </pre>
     *
     * <code>repeated .proto.InfoValue infoList = 1;</code>
     */
    public com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValueOrBuilder getInfoListOrBuilder(
        int index) {
      return infoList_.get(index);
    }
    private void ensureInfoListIsMutable() {
      com.google.protobuf.Internal.ProtobufList<com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue> tmp = infoList_;
      if (!tmp.isModifiable()) {
        infoList_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <pre>
     * 对象列表
     * </pre>
     *
     * <code>repeated .proto.InfoValue infoList = 1;</code>
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setInfoList(
        int index, com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue value) {
      value.getClass();  // minimal bytecode null check
      ensureInfoListIsMutable();
      infoList_.set(index, value);
    }
    /**
     * <pre>
     * 对象列表
     * </pre>
     *
     * <code>repeated .proto.InfoValue infoList = 1;</code>
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void addInfoList(com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue value) {
      value.getClass();  // minimal bytecode null check
      ensureInfoListIsMutable();
      infoList_.add(value);
    }
    /**
     * <pre>
     * 对象列表
     * </pre>
     *
     * <code>repeated .proto.InfoValue infoList = 1;</code>
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void addInfoList(
        int index, com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue value) {
      value.getClass();  // minimal bytecode null check
      ensureInfoListIsMutable();
      infoList_.add(index, value);
    }
    /**
     * <pre>
     * 对象列表
     * </pre>
     *
     * <code>repeated .proto.InfoValue infoList = 1;</code>
     */
    private void addAllInfoList(
        java.lang.Iterable<? extends com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue> values) {
      ensureInfoListIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, infoList_);
    }
    /**
     * <pre>
     * 对象列表
     * </pre>
     *
     * <code>repeated .proto.InfoValue infoList = 1;</code>
     */
    private void clearInfoList() {
      infoList_ = emptyProtobufList();
    }
    /**
     * <pre>
     * 对象列表
     * </pre>
     *
     * <code>repeated .proto.InfoValue infoList = 1;</code>
     */
    private void removeInfoList(int index) {
      ensureInfoListIsMutable();
      infoList_.remove(index);
    }

    public static com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValueList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValueList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValueList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValueList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValueList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValueList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValueList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValueList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValueList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValueList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValueList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValueList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValueList prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code proto.InfoValueList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValueList, Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.InfoValueList)
        com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValueListOrBuilder {
      // Construct using com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValueList.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * 对象列表
       * </pre>
       *
       * <code>repeated .proto.InfoValue infoList = 1;</code>
       */
      @java.lang.Override
      public java.util.List<com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue> getInfoListList() {
        return java.util.Collections.unmodifiableList(
            instance.getInfoListList());
      }
      /**
       * <pre>
       * 对象列表
       * </pre>
       *
       * <code>repeated .proto.InfoValue infoList = 1;</code>
       */
      @java.lang.Override
      public int getInfoListCount() {
        return instance.getInfoListCount();
      }/**
       * <pre>
       * 对象列表
       * </pre>
       *
       * <code>repeated .proto.InfoValue infoList = 1;</code>
       */
      @java.lang.Override
      public com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue getInfoList(int index) {
        return instance.getInfoList(index);
      }
      /**
       * <pre>
       * 对象列表
       * </pre>
       *
       * <code>repeated .proto.InfoValue infoList = 1;</code>
       */
      public Builder setInfoList(
          int index, com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue value) {
        copyOnWrite();
        instance.setInfoList(index, value);
        return this;
      }
      /**
       * <pre>
       * 对象列表
       * </pre>
       *
       * <code>repeated .proto.InfoValue infoList = 1;</code>
       */
      public Builder setInfoList(
          int index, com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue.Builder builderForValue) {
        copyOnWrite();
        instance.setInfoList(index,
            builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * 对象列表
       * </pre>
       *
       * <code>repeated .proto.InfoValue infoList = 1;</code>
       */
      public Builder addInfoList(com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue value) {
        copyOnWrite();
        instance.addInfoList(value);
        return this;
      }
      /**
       * <pre>
       * 对象列表
       * </pre>
       *
       * <code>repeated .proto.InfoValue infoList = 1;</code>
       */
      public Builder addInfoList(
          int index, com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue value) {
        copyOnWrite();
        instance.addInfoList(index, value);
        return this;
      }
      /**
       * <pre>
       * 对象列表
       * </pre>
       *
       * <code>repeated .proto.InfoValue infoList = 1;</code>
       */
      public Builder addInfoList(
          com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue.Builder builderForValue) {
        copyOnWrite();
        instance.addInfoList(builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * 对象列表
       * </pre>
       *
       * <code>repeated .proto.InfoValue infoList = 1;</code>
       */
      public Builder addInfoList(
          int index, com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue.Builder builderForValue) {
        copyOnWrite();
        instance.addInfoList(index,
            builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * 对象列表
       * </pre>
       *
       * <code>repeated .proto.InfoValue infoList = 1;</code>
       */
      public Builder addAllInfoList(
          java.lang.Iterable<? extends com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue> values) {
        copyOnWrite();
        instance.addAllInfoList(values);
        return this;
      }
      /**
       * <pre>
       * 对象列表
       * </pre>
       *
       * <code>repeated .proto.InfoValue infoList = 1;</code>
       */
      public Builder clearInfoList() {
        copyOnWrite();
        instance.clearInfoList();
        return this;
      }
      /**
       * <pre>
       * 对象列表
       * </pre>
       *
       * <code>repeated .proto.InfoValue infoList = 1;</code>
       */
      public Builder removeInfoList(int index) {
        copyOnWrite();
        instance.removeInfoList(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.InfoValueList)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValueList();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "infoList_",
              com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValue.class,
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValueList> parser = PARSER;
          if (parser == null) {
            synchronized (com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValueList.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValueList>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:proto.InfoValueList)
    private static final com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValueList DEFAULT_INSTANCE;
    static {
      InfoValueList defaultInstance = new InfoValueList();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        InfoValueList.class, defaultInstance);
    }

    public static com.example.gitsample.system.proto.data.InfoValueOuterClass.InfoValueList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<InfoValueList> PARSER;

    public static com.google.protobuf.Parser<InfoValueList> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
